#!/bin/sh

#echo "Check that we have NEXT_PUBLIC vars"
#test -n "$NEXT_PUBLIC_API_SERVER_HOST"

find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i -e "s#APP_NEXT_PUBLIC_API_SERVER_HOST#$NEXT_PUBLIC_API_SERVER_HOST#g" -e "s#APP_NEXT_PUBLIC_HOST#$NEXT_PUBLIC_HOST#g" -e "s#APP_NEXT_PUBLIC_NODE_ENV#$NEXT_PUBLIC_NODE_ENV#g" -e "s#APP_NEXT_PUBLIC_AUTH0_DOMAIN#$NEXT_PUBLIC_AUTH0_DOMAIN#g" -e "s#APP_NEXT_PUBLIC_AUTH0_CLIENT_ID#$NEXT_PUBLIC_AUTH0_CLIENT_ID#g" -e "s#APP_NEXT_PUBLIC_AUTH0_REDIRECT_URI#$NEXT_PUBLIC_AUTH0_REDIRECT_URI#g" -e "s#APP_NEXT_PUBLIC_AUTH0_REALM#$NEXT_PUBLIC_AUTH0_REALM#g" -e "s#APP_NEXT_PUBLIC_STRAPI_HOST#$NEXT_PUBLIC_STRAPI_HOST#g" -e "s#APP_NEXT_PUBLIC_STRIPE_PUBLIC_KEY#$NEXT_PUBLIC_STRIPE_PUBLIC_KEY#g" -e "s#APP_NEXT_PUBLIC_LOGROCKET_PROJECT#$NEXT_PUBLIC_LOGROCKET_PROJECT#g" -e "s#APP_NEXT_PUBLIC_HOTJAR_ID#$NEXT_PUBLIC_HOTJAR_ID#g" -e "s#APP_NEXT_PUBLIC_VWO_ID#$NEXT_PUBLIC_VWO_ID#g"

echo "Starting Nextjs"
exec "$@"
