import Head from "next/head";
import NewsletterBox from "../components/NewsletterBox";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>twoMatches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </Head>

      <main className="flex h-screen justify-center items-center">
        <NewsletterBox />
      </main>
    </div>
  );
}
