name: Cypress Tests

on: [push]

env:
  NEXT_PUBLIC_NODE_ENV: development
  NEXT_PUBLIC_API_SERVER_HOST: http://localhost:5000
  NEXT_PUBLIC_AUTH0_DOMAIN: dev-two-matches.us.auth0.com
  NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.DEV_AUTH0_CLIENT_ID}}
  NEXT_PUBLIC_AUTH0_REDIRECT_URI: http://localhost:3000/authorize
  NEXT_PUBLIC_AUTH0_REALM: ${{ secrets.DEV_AUTH0_REALM}}
  NEXT_PUBLIC_STRAPI_HOST: https://demo.twomatches.xyz/strapi

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
